package com.p118pd.sdk;

import com.facebook.react.modules.netinfo.NetInfoModule;
import java.util.HashMap;

/* renamed from: com.pd.sdk.oOOO00O  reason: case insensitive filesystem */
public class C8090oOOO00O {
    public static HashMap<Integer, HashMap<String, String>> OooO00o = new HashMap<>();
    public static HashMap<String, String> OooO0O0 = new HashMap<>();
    public static HashMap<String, String> OooO0OO = new HashMap<>();
    public static HashMap<String, String> OooO0Oo = new HashMap<>();
    public static HashMap<String, String> OooO0o0 = new HashMap<>();

    static {
        OooO00o.put(1, OooO0O0);
        OooO00o.put(110, OooO0OO);
        OooO00o.put(101, OooO0Oo);
        OooO00o.put(101, OooO0o0);
        OooO0OO.put("3IVX", "3ivx MPEG-4");
        OooO0OO.put("3IV1", "3ivx MPEG-4 v1");
        OooO0OO.put("3IV2", "3ivx MPEG-4 v2");
        OooO0OO.put("avr ", "AVR-JPEG");
        OooO0OO.put("base", "Base");
        OooO0OO.put("WRLE", "BMP");
        OooO0OO.put("cvid", "Cinepak");
        OooO0OO.put("clou", "Cloud");
        OooO0OO.put("cmyk", "CMYK");
        OooO0OO.put("yuv2", "ComponentVideo");
        OooO0OO.put("yuvu", "ComponentVideoSigned");
        OooO0OO.put("yuvs", "ComponentVideoUnsigned");
        OooO0OO.put("dvc ", "DVC-NTSC");
        OooO0OO.put("dvcp", "DVC-PAL");
        OooO0OO.put("dvpn", "DVCPro-NTSC");
        OooO0OO.put("dvpp", "DVCPro-PAL");
        OooO0OO.put("fire", "Fire");
        OooO0OO.put("flic", "FLC");
        OooO0OO.put("b48r", "48RGB");
        OooO0OO.put("gif ", "GIF");
        OooO0OO.put("smc ", "Graphics");
        OooO0OO.put("h261", "Apple H261");
        OooO0OO.put("h263", "Apple VC H.263");
        OooO0OO.put("IV41", "Indeo4");
        OooO0OO.put("jpeg", "JPEG");
        OooO0OO.put("PNTG", "MacPaint");
        OooO0OO.put("msvc", "Microsoft Video1");
        OooO0OO.put("mjpa", "Apple Motion JPEG-A");
        OooO0OO.put("mjpb", "Apple Motion JPEG-B");
        OooO0OO.put("myuv", "MPEG YUV420");
        OooO0OO.put("dmb1", "OpenDML JPEG");
        OooO0OO.put("kpcd", "PhotoCD");
        OooO0OO.put("8BPS", "Planar RGB");
        OooO0OO.put("png ", "PNG");
        OooO0OO.put("qdrw", "QuickDraw");
        OooO0OO.put("qdgx", "QuickDrawGX");
        OooO0OO.put("raw ", "RAW");
        OooO0OO.put(".SGI", "SGI");
        OooO0OO.put("b16g", "16Gray");
        OooO0OO.put("b64a", "64ARGB");
        OooO0OO.put("SVQ1", "Sorenson Video 1");
        OooO0OO.put("SVQ3", "Sorenson Video 3");
        OooO0OO.put("syv9", "Sorenson YUV9");
        OooO0OO.put("tga ", "Targa");
        OooO0OO.put("b32a", "32AlphaGray");
        OooO0OO.put("tiff", "TIFF");
        OooO0OO.put("path", "Vector");
        OooO0OO.put("rpza", "Video (Road Pizza)");
        OooO0OO.put("ripl", "WaterRipple");
        OooO0OO.put("WRAW", "Windows RAW");
        OooO0OO.put("y420", "YUV420");
        OooO0OO.put("avc1", "H.264");
        OooO0OO.put("mp4v", "MPEG-4");
        OooO0OO.put("MP4V", "MPEG-4");
        OooO0OO.put("dvhp", "DVCPRO HD 720p60");
        OooO0OO.put("hdv2", "HDV 1080i60");
        OooO0OO.put("dvc+", "DV/DVCPRO - NTSC");
        OooO0OO.put("mx5p", "MPEG2 IMX 635/50 50mb/s");
        OooO0OO.put("mx3n", "MPEG2 IMX 635/50 30mb/s");
        OooO0OO.put("dv5p", "DVCPRO50");
        OooO0OO.put("hdv3", "HDV Final Cut Pro");
        OooO0OO.put("rle ", "Animation");
        OooO0OO.put("rle ", "Animation");
        OooO0OO.put("2vuY", "Uncompressed Y'CbCr, 8-bit-per-component 4:2:2");
        OooO0OO.put("v308", "Uncompressed Y'CbCr, 8-bit-per-component 4:4:4");
        OooO0OO.put("v408", "Uncompressed Y'CbCr, 8-bit-per-component 4:4:4:4");
        OooO0OO.put("v216", "Uncompressed Y'CbCr, 10, 12, 14, or 16-bit-per-component 4:2:2");
        OooO0OO.put("v410", "Uncompressed Y'CbCr, 10-bit-per-component 4:4:4");
        OooO0OO.put("v210", "Uncompressed Y'CbCr, 10-bit-per-component 4:2:2");
        OooO0Oo.put(NetInfoModule.CONNECTION_TYPE_NONE_DEPRECATED, "");
        OooO0Oo.put("raw ", "Uncompressed in offset-binary format");
        OooO0Oo.put("twos", "Uncompressed in two's-complement format");
        OooO0Oo.put("sowt", "16-bit little-endian, twos-complement");
        OooO0Oo.put("MAC3", "MACE 3:1");
        OooO0Oo.put("MAC6", "MACE 6:1");
        OooO0Oo.put("ima4", "IMA 4:1");
        OooO0Oo.put("fl32", "32-bit floating point");
        OooO0Oo.put("fl64", "64-bit floating point");
        OooO0Oo.put("in24", "24-bit integer");
        OooO0Oo.put("in32", "32-bit integer");
        OooO0Oo.put("ulaw", "uLaw 2:1");
        OooO0Oo.put("alaw", "uLaw 2:1");
        OooO0Oo.put("ms\u0000\u0002", "Microsoft ADPCM-ACM code 2");
        OooO0Oo.put("ms\u0000\u0011", "DVI/Intel IMAADPCM-ACM code 17");
        OooO0Oo.put("dvca", "DV Audio");
        OooO0Oo.put("QDMC", "QDesign music");
        OooO0Oo.put("QDM2", "QDesign music version 2");
        OooO0Oo.put("Qclp", "QUALCOMM PureVoice");
        OooO0Oo.put("ms\u0000U", "MPEG-1 layer 3, CBR only (pre-QT4.1)");
        OooO0Oo.put(".mp3", "MPEG-1 layer 3, CBR & VBR (QT4.1 and later)");
        OooO0Oo.put("mp4a", "MPEG-4, Advanced Audio Coding (AAC)");
        OooO0Oo.put("ac-3", "Digital Audio Compression Standard (AC-3, Enhanced AC-3)");
        OooO0Oo.put("aac ", "ISO/IEC 144963-3 AAC");
        OooO0Oo.put("agsm", "Apple GSM 10:1");
        OooO0Oo.put("alac", "Apple Lossless Audio Codec");
        OooO0Oo.put("conv", "Sample Format");
        OooO0Oo.put("dvi ", "DV 4:1");
        OooO0Oo.put("eqal", "Frequency Equalizer");
        OooO0Oo.put("lpc ", "LPC 23:1");
        OooO0Oo.put("mixb", "8-bit Mixer");
        OooO0Oo.put("mixw", "16-bit Mixer");
        OooO0Oo.put("MS\u0000\u0002", "Microsoft ADPCM");
        OooO0Oo.put("MS\u0000\u0011", "DV IMA");
        OooO0Oo.put("MS\u0000U", "MPEG3");
        OooO0Oo.put("ratb", "8-bit Rate");
        OooO0Oo.put("ratw", "16-bit Rate");
        OooO0Oo.put("sour", "Sound Source");
        OooO0Oo.put("str1", "Iomega MPEG layer II");
        OooO0Oo.put("str2", "Iomega MPEG *layer II");
        OooO0Oo.put("str3", "Iomega MPEG **layer II");
        OooO0Oo.put("str4", "Iomega MPEG ***layer II");
        OooO0Oo.put("lpcm", "Linear Pulse Code Modulation");
        OooO0O0.put("3g2a", "3GPP2 Media (.3G2) compliant with 3GPP2 C.S0050-0 V1.0");
        OooO0O0.put("3g2b", "3GPP2 Media (.3G2) compliant with 3GPP2 C.S0050-A V1.0.0");
        OooO0O0.put("3g2c", "3GPP2 Media (.3G2) compliant with 3GPP2 C.S0050-B v1.0");
        OooO0O0.put("3ge6", "3GPP (.3GP) Release 6 MBMS Extended Presentations");
        OooO0O0.put("3ge7", "3GPP (.3GP) Release 7 MBMS Extended Presentations");
        OooO0O0.put("3gg6", "3GPP Release 6 General Profile");
        OooO0O0.put("3gp1", "3GPP Media (.3GP) Release 1 (probably non-existent)");
        OooO0O0.put("3gp2", "3GPP Media (.3GP) Release 2 (probably non-existent)");
        OooO0O0.put("3gp3", "3GPP Media (.3GP) Release 3 (probably non-existent)");
        OooO0O0.put("3gp4", "3GPP Media (.3GP) Release 4");
        OooO0O0.put("3gp5", "3GPP Media (.3GP) Release 5");
        OooO0O0.put("3gp6", "3GPP Media (.3GP) Release 6 Basic Profile");
        OooO0O0.put("3gp6", "3GPP Media (.3GP) Release 6 Progressive Download");
        OooO0O0.put("3gp6", "3GPP Media (.3GP) Release 6 Streaming Servers");
        OooO0O0.put("3gs7", "3GPP Media (.3GP) Release 7 Streaming Servers");
        OooO0O0.put("avc1", "MP4 Base w/ AVC ext [ISO 14496-12:2005]");
        OooO0O0.put("CAEP", "Canon Digital Camera");
        OooO0O0.put("caqv", "Casio Digital Camera");
        OooO0O0.put("CDes", "Convergent Design");
        OooO0O0.put("da0a", "DMB MAF w/ MPEG Layer II aud, MOT slides, DLS, JPG/PNG/MNG images");
        OooO0O0.put("da0b", "DMB MAF, extending DA0A, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("da1a", "DMB MAF audio with ER-BSAC audio, JPG/PNG/MNG images");
        OooO0O0.put("da1b", "DMB MAF, extending da1a, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("da2a", "DMB MAF aud w/ HE-AAC v2 aud, MOT slides, DLS, JPG/PNG/MNG images");
        OooO0O0.put("da2b", "DMB MAF, extending da2a, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("da3a", "DMB MAF aud with HE-AAC aud, JPG/PNG/MNG images");
        OooO0O0.put("da3b", "DMB MAF, extending da3a w/ BIFS, 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("dmb1", "DMB MAF supporting all the components defined in the specification");
        OooO0O0.put("dmpf", "Digital Media Project");
        OooO0O0.put("drc1", "Dirac (wavelet compression), encapsulated in ISO base media (MP4)");
        OooO0O0.put("dv1a", "DMB MAF vid w/ AVC vid, ER-BSAC aud, BIFS, JPG/PNG/MNG images, TS");
        OooO0O0.put("dv1b", "DMB MAF, extending dv1a, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("dv2a", "DMB MAF vid w/ AVC vid, HE-AAC v2 aud, BIFS, JPG/PNG/MNG images, TS");
        OooO0O0.put("dv2b", "DMB MAF, extending dv2a, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("dv3a", "DMB MAF vid w/ AVC vid, HE-AAC aud, BIFS, JPG/PNG/MNG images, TS");
        OooO0O0.put("dv3b", "DMB MAF, extending dv3a, with 3GPP timed text, DID, TVA, REL, IPMP");
        OooO0O0.put("dvr1", "DVB (.DVB) over RTP");
        OooO0O0.put("dvt1", "DVB (.DVB) over MPEG-2 Transport Stream");
        OooO0O0.put("F4V ", "Video for Adobe Flash Player 9+ (.F4V)");
        OooO0O0.put("F4P ", "Protected Video for Adobe Flash Player 9+ (.F4P)");
        OooO0O0.put("F4A ", "Audio for Adobe Flash Player 9+ (.F4A)");
        OooO0O0.put("F4B ", "Audio Book for Adobe Flash Player 9+ (.F4B)");
        OooO0O0.put("isc2", "ISMACryp 2.0 Encrypted File");
        OooO0O0.put("iso2", "MP4 Base Media v2 [ISO 14496-12:2005]");
        OooO0O0.put("isom", "MP4  Base Media v1 [IS0 14496-12:2003]");
        OooO0O0.put("JP2 ", "JPEG 2000 Image (.JP2) [ISO 15444-1 ?]");
        OooO0O0.put("JP20", "Unknown, from GPAC samples (prob non-existent)");
        OooO0O0.put("jpm ", "JPEG 2000 Compound Image (.JPM) [ISO 15444-6]");
        OooO0O0.put("jpx ", "JPEG 2000 w/ extensions (.JPX) [ISO 15444-2]");
        OooO0O0.put("KDDI", "3GPP2 EZmovie for KDDI 3G cellphones");
        OooO0O0.put("M4A ", "Apple iTunes AAC-LC (.M4A) Audio");
        OooO0O0.put("M4B ", "Apple iTunes AAC-LC (.M4B) Audio Book");
        OooO0O0.put("M4P ", "Apple iTunes AAC-LC (.M4P) AES Protected Audio");
        OooO0O0.put("M4V ", "Apple iTunes Video (.M4V) Video");
        OooO0O0.put("M4VH", "Apple TV (.M4V)");
        OooO0O0.put("M4VP", "Apple iPhone (.M4V)");
        OooO0O0.put("mj2s", "Motion JPEG 2000 [ISO 15444-3] Simple Profile");
        OooO0O0.put("mjp2", "Motion JPEG 2000 [ISO 15444-3] General Profile");
        OooO0O0.put("mmp4", "MPEG-4/3GPP Mobile Profile (.MP4 / .3GP) (for NTT)");
        OooO0O0.put("mp21", "MPEG-21 [ISO/IEC 21000-9]");
        OooO0O0.put("mp41", "MP4 v1 [ISO 14496-1:ch13]");
        OooO0O0.put("mp42", "MP4 v2 [ISO 14496-14]");
        OooO0O0.put("mp71", "MP4 w/ MPEG-7 Metadata [per ISO 14496-12]");
        OooO0O0.put("MPPI", "Photo Player, MAF [ISO/IEC 23000-3]");
        OooO0O0.put("mqt ", "Sony / Mobile QuickTime (.MQV)  US Patent 7,477,830 (Sony Corp)");
        OooO0O0.put("MSNV", "MPEG-4 (.MP4) for SonyPSP");
        OooO0O0.put("NDAS", "MP4 v2 [ISO 14496-14] Nero Digital AAC Audio");
        OooO0O0.put("NDSC", "MPEG-4 (.MP4) Nero Cinema Profile");
        OooO0O0.put("NDSH", "MPEG-4 (.MP4) Nero HDTV Profile");
        OooO0O0.put("NDSM", "MPEG-4 (.MP4) Nero Mobile Profile");
        OooO0O0.put("NDSP", "MPEG-4 (.MP4) Nero Portable Profile");
        OooO0O0.put("NDSS", "MPEG-4 (.MP4) Nero Standard Profile");
        OooO0O0.put("NDXC", "H.264/MPEG-4 AVC (.MP4) Nero Cinema Profile");
        OooO0O0.put("NDXH", "H.264/MPEG-4 AVC (.MP4) Nero HDTV Profile");
        OooO0O0.put("NDXM", "H.264/MPEG-4 AVC (.MP4) Nero Mobile Profile");
        OooO0O0.put("NDXP", "H.264/MPEG-4 AVC (.MP4) Nero Portable Profile");
        OooO0O0.put("NDXS", "H.264/MPEG-4 AVC (.MP4) Nero Standard Profile");
        OooO0O0.put("odcf", "OMA DCF DRM Format 2.0 (OMA-TS-DRM-DCF-V2_0-20060303-A)");
        OooO0O0.put("opf2", "OMA PDCF DRM Format 2.1 (OMA-TS-DRM-DCF-V2_1-20070724-C)");
        OooO0O0.put("opx2", "OMA PDCF DRM + XBS extensions (OMA-TS-DRM_XBS-V1_0-20070529-C)");
        OooO0O0.put("pana", "Panasonic Digital Camera");
        OooO0O0.put("qt  ", "Apple QuickTime (.MOV/QT)");
        OooO0O0.put("ROSS", "Ross Video");
        OooO0O0.put("sdv ", "SD Memory Card Video");
        OooO0O0.put("ssc1", "Samsung stereoscopic, single stream (patent pending, see notes)");
        OooO0O0.put("ssc2", "Samsung stereoscopic, dual stream (patent pending, see notes)");
        OooO0o0.put(" KD ", "Kodak");
        OooO0o0.put("AR.D", "Parrot AR.Drone");
        OooO0o0.put("FFMP", "FFmpeg");
        OooO0o0.put("GIC ", "General Imaging Co.");
        OooO0o0.put("KMPI", "Konica-Minolta");
        OooO0o0.put("NIKO", "Nikon");
        OooO0o0.put("SMI ", "Sorenson Media Inc.");
        OooO0o0.put("ZORA", "Zoran Corporation");
        OooO0o0.put("appl", "Apple");
        OooO0o0.put("fe20", "Olympus (fe20)");
        OooO0o0.put("kdak", "Kodak");
        OooO0o0.put("leic", "Leica");
        OooO0o0.put("mino", "Minolta");
        OooO0o0.put("niko", "Nikon");
        OooO0o0.put("olym", "Olympus");
        OooO0o0.put("pana", "Panasonic");
        OooO0o0.put("pent", "Pentax");
        OooO0o0.put("pr01", "Olympus (pr01)");
        OooO0o0.put("sany", "Sanyo");
    }

    public static String OooO00o(int i, String str) {
        return (!OooO00o.containsKey(Integer.valueOf(i)) || !OooO00o.get(Integer.valueOf(i)).containsKey(str)) ? "Unknown" : OooO00o.get(Integer.valueOf(i)).get(str);
    }

    public static void OooO00o(int i, String str, C8091oOOO00Oo oooo00oo) {
        oooo00oo.m19648OooO00o(i, OooO00o(i, str));
    }
}
