package com.p118pd.sdk;

import java.io.PrintStream;
import java.math.BigInteger;
import java.security.SecureRandom;
import org.bouncycastle.crypto.CryptoException;

/* renamed from: com.pd.sdk.IIiiLl */
public class IIiiLl {
    public static BigInteger OooO00o(BigInteger bigInteger) {
        I1li1Ll r0 = new I1li1Ll();
        byte[] byteArray = bigInteger.toByteArray();
        byte[] bArr = new byte[r0.OooO0O0()];
        r0.update(byteArray, 0, byteArray.length);
        r0.OooO00o(bArr, 0);
        return new BigInteger(bArr);
    }

    public static void OooO00o(String[] strArr) throws CryptoException {
        C6648liIIL r14 = C1L.OooO0OO;
        BigInteger OooO0O0 = r14.OooO0O0();
        BigInteger OooO0OO = r14.OooO0OO();
        BigInteger OooO00o = r14.OooO00o();
        System.out.println("********* Initialization **********");
        System.out.println("Public parameters for the cyclic group:");
        PrintStream printStream = System.out;
        printStream.println("p (" + OooO0O0.bitLength() + " bits): " + OooO0O0.toString(16));
        PrintStream printStream2 = System.out;
        printStream2.println("q (" + OooO0OO.bitLength() + " bits): " + OooO0OO.toString(16));
        PrintStream printStream3 = System.out;
        printStream3.println("g (" + OooO0O0.bitLength() + " bits): " + OooO00o.toString(16));
        PrintStream printStream4 = System.out;
        StringBuilder sb = new StringBuilder();
        sb.append("p mod q = ");
        sb.append(OooO0O0.mod(OooO0OO).toString(16));
        printStream4.println(sb.toString());
        PrintStream printStream5 = System.out;
        printStream5.println("g^{q} mod p = " + OooO00o.modPow(OooO0OO, OooO0O0).toString(16));
        System.out.println("");
        PrintStream printStream6 = System.out;
        printStream6.println("(Secret passwords used by Alice and Bob: \"" + "password" + "\" and \"" + "password" + "\")\n");
        I1li1Ll r9 = new I1li1Ll();
        SecureRandom secureRandom = new SecureRandom();
        C9547LL r11 = new C9547LL("alice", "password".toCharArray(), r14, r9, secureRandom);
        C9547LL r12 = new C9547LL("bob", "password".toCharArray(), r14, r9, secureRandom);
        C6374iL OooO00o2 = r11.m21606OooO00o();
        C6374iL OooO00o3 = r12.m21606OooO00o();
        System.out.println("************ Round 1 **************");
        System.out.println("Alice sends to Bob: ");
        PrintStream printStream7 = System.out;
        printStream7.println("g^{x1}=" + OooO00o2.m17486OooO00o().toString(16));
        PrintStream printStream8 = System.out;
        printStream8.println("g^{x2}=" + OooO00o2.OooO0O0().toString(16));
        PrintStream printStream9 = System.out;
        printStream9.println("KP{x1}={" + OooO00o2.m17487OooO00o()[0].toString(16) + "};{" + OooO00o2.m17487OooO00o()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        PrintStream printStream10 = System.out;
        printStream10.println("KP{x2}={" + OooO00o2.m17488OooO0O0()[0].toString(16) + "};{" + OooO00o2.m17488OooO0O0()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        System.out.println("");
        System.out.println("Bob sends to Alice: ");
        PrintStream printStream11 = System.out;
        printStream11.println("g^{x3}=" + OooO00o3.m17486OooO00o().toString(16));
        PrintStream printStream12 = System.out;
        printStream12.println("g^{x4}=" + OooO00o3.OooO0O0().toString(16));
        PrintStream printStream13 = System.out;
        printStream13.println("KP{x3}={" + OooO00o3.m17487OooO00o()[0].toString(16) + "};{" + OooO00o3.m17487OooO00o()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        PrintStream printStream14 = System.out;
        printStream14.println("KP{x4}={" + OooO00o3.m17488OooO0O0()[0].toString(16) + "};{" + OooO00o3.m17488OooO0O0()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        System.out.println("");
        r11.OooO00o(OooO00o3);
        System.out.println("Alice checks g^{x4}!=1: OK");
        System.out.println("Alice checks KP{x3}: OK");
        System.out.println("Alice checks KP{x4}: OK");
        System.out.println("");
        r12.OooO00o(OooO00o2);
        System.out.println("Bob checks g^{x2}!=1: OK");
        System.out.println("Bob checks KP{x1},: OK");
        System.out.println("Bob checks KP{x2},: OK");
        System.out.println("");
        C1iLL1 OooO00o4 = r11.m21607OooO00o();
        C1iLL1 OooO00o5 = r12.m21607OooO00o();
        System.out.println("************ Round 2 **************");
        System.out.println("Alice sends to Bob: ");
        PrintStream printStream15 = System.out;
        printStream15.println("A=" + OooO00o4.m21312OooO00o().toString(16));
        PrintStream printStream16 = System.out;
        printStream16.println("KP{x2*s}={" + OooO00o4.m21313OooO00o()[0].toString(16) + "},{" + OooO00o4.m21313OooO00o()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        System.out.println("");
        System.out.println("Bob sends to Alice");
        PrintStream printStream17 = System.out;
        printStream17.println("B=" + OooO00o5.m21312OooO00o().toString(16));
        PrintStream printStream18 = System.out;
        printStream18.println("KP{x4*s}={" + OooO00o5.m21313OooO00o()[0].toString(16) + "},{" + OooO00o5.m21313OooO00o()[1].toString(16) + C7522o0Ooo0o.OooO0Oo);
        System.out.println("");
        r11.OooO00o(OooO00o5);
        System.out.println("Alice checks KP{x4*s}: OK\n");
        r12.OooO00o(OooO00o4);
        System.out.println("Bob checks KP{x2*s}: OK\n");
        BigInteger OooO00o6 = r11.m21608OooO00o();
        BigInteger OooO00o7 = r12.m21608OooO00o();
        System.out.println("********* After round 2 ***********");
        PrintStream printStream19 = System.out;
        printStream19.println("Alice computes key material \t K=" + OooO00o6.toString(16));
        PrintStream printStream20 = System.out;
        printStream20.println("Bob computes key material \t K=" + OooO00o7.toString(16));
        System.out.println();
        OooO00o(OooO00o6);
        OooO00o(OooO00o7);
        C6408ilIl OooO00o8 = r11.OooO00o(OooO00o6);
        C6408ilIl OooO00o9 = r12.OooO00o(OooO00o7);
        System.out.println("************ Round 3 **************");
        System.out.println("Alice sends to Bob: ");
        PrintStream printStream21 = System.out;
        printStream21.println("MacTag=" + OooO00o8.m17525OooO00o().toString(16));
        System.out.println("");
        System.out.println("Bob sends to Alice: ");
        PrintStream printStream22 = System.out;
        printStream22.println("MacTag=" + OooO00o9.m17525OooO00o().toString(16));
        System.out.println("");
        r11.OooO00o(OooO00o9, OooO00o6);
        System.out.println("Alice checks MacTag: OK\n");
        r12.OooO00o(OooO00o8, OooO00o7);
        System.out.println("Bob checks MacTag: OK\n");
        System.out.println();
        System.out.println("MacTags validated, therefore the keying material matches.");
    }
}
